<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0"/>
        <PackageReference Include="NUnit" Version="4.3.2"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.7.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0"/>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="UniTask" Version="2.5.11"/>
        <PackageReference Include="ObservableCollections" Version="3.3.4"/>
        <PackageReference Include="ObservableCollections.R3" Version="3.3.4"/>
        <PackageReference Include="R3" Version="1.3.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fenestra\Fenestra.csproj"/>
    </ItemGroup>

</Project>